apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ project }}-certbot-cronjob
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ project }}-letsencrypt
        spec:
          containers:
          - env:
            - name: DOMAINS
              value: {{ hostname }}
            - name: EMAIL
              value: {{ certbot.email }}
            - name: SECRET
              value: {{ project }}secret
            - name: DEPLOYMENT
              value: {{ deployment }}
            - name: TEST_CERT
              value: "{{ certbot.test }}"
            - name: RENEW
              value: "1"
            image: asksven/certbot:17
            imagePullPolicy: Always
            name: {{ project }}-certbot
            volumeMounts:
            - mountPath: /letsencrypt
              name: {{ project }}-cert-volume
          volumes:
          - name: {{ project }}-cert-volume
            persistentVolumeClaim:
              claimName: {{ project }}-cert-pvc
          imagePullSecrets:
          - name: regcred
          restartPolicy: Never
  schedule: 0 3 * * *
  suspend: false