apiVersion: batch/v1
kind: Job
metadata:
  name: {{ project }}-letsencrypt
  labels:
    app: {{ project }}-letsencrypt
spec:
  template:
    metadata:
      name: {{ project }}-letsencrypt
      labels:
        app: {{ project }}-letsencrypt
    spec:
      serviceAccountName: certbot-sa
      containers:
      - image: asksven/certbot:17
        name: {{ project }}-letsencrypt
        imagePullPolicy: Always
        ports:
        - name: letsencrypt
          containerPort: 80
        env:
        - name: DOMAINS
          value: {{ hostname }}
        - name: EMAIL
          value: {{ certbot.email }}
        - name: SECRET
          value: {{ project }}secret
        - name: DEPLOYMENT
          value: {{ deployment }}
        - name: TEST_CERT
          value: "{{ certbot.test }}"
        - name: RENEW
          value: "0"
        volumeMounts:
        - mountPath: /letsencrypt
          name: {{ project }}-cert-volume
      volumes:
        - name: {{ project }}-cert-volume
          persistentVolumeClaim:
            claimName: {{ project }}-cert-pvc
      restartPolicy: Never