apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ project }}-cert-pvc
  labels:
    app: {{ project }}-letsencrypt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ resources.certPvc }}