apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ project }}-letsencrypt
  name: {{ project }}-letsencrypt
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ project }}-letsencrypt
  type: ClusterIP
