apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ ingress.name }}
  annotations:
    kubernetes.io/ingress.class: {{ ingress.class }}
spec:
  rules:
  - host: {{ hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ service.name }}
          servicePort: {{ service.port }}
      - path: /.well-known
        backend:
          serviceName: {{ project }}-letsencrypt
          servicePort: 80
  tls:
  - hosts: 
    - {{ hostname }}
    secretName: {{ project }}secret 
